### ISSUE TITLE
UpsertMany wrong order in resultset

### ISSUE THREAD

**Issue by henkosch** [jonwagner/Insight.Database.Schema#34]
Hello!

I'm trying to use the UpsertMany stored procedure generated by AutoProc to update and insert rows into a table. I'm using the InsertList() extension method to call the procedure, because I want to get the ids of the inserted rows written back to the appropriate objects. Unfortunately UpsertMany gives the ids back in the wrong order, so they get written back in different objects where they came from. 

Consider the following table:

```
User (Id int, Name nvarchar(max));
```

It has the following content:

```
(1, 'User 1'),
(2, 'User 2')
```

Then I call UpsertUsers like this:

```
connection.InsertList("UpsertUsers", new List<User> {
  new User { Id = 1, Name = "User 1" },
  new User { Id = 2, Name = "User 2 updated" },
  new User { Name = "User 3 inserted" }
});
```

UpsertUsers returns with the following resultset:

```
(3),
(1),
(2)
```

This means that the objects in the list will get the wrong ids, the result will be:

```
User (Id = 3, Name = "User 1")
User (Id = 1, Name = "User 2 updated")
User (Id = 2, Name = "User 3 inserted")
```

Which is completely wrong. 

Is there any other way to call UpsertUsers and get back the correct ids or is this a bug?

**Comment by jonwagner** [comment]
v3.x (coming soon) uses TVPs with hidden identity columns to solve this for insert and upsert.
