### ISSUE TITLE
AUTOPROC not regenerated after change in table

### ISSUE THREAD

**Issue by jeroenbu** [jonwagner/Insight.Database.Schema#40]
Hi,

When I remove or add a column in a table AFTER the initial generation of the AUTOPROCs, the procs don't seem to reflect that change; the removed or added column is still referenced in (for example) the Find-procedure.
Calling the installer with AllowRepair = true doesn't help.

Thx,

Jeroen

**Comment by jonwagner** [comment]
I ran some tests today, and it *should* be detecting the dependencies. Your issues probably have something to do with the other two issues #38 and #39. If you send me your SQL script, I can run it though the verifier before I do the next build.

**Comment by jonwagner** [comment]
From what I can tell, this is working properly. I did run through the script you sent me, but I had to cut and paste from the different files, so I may not have run your exact scenario.

Give it a try with v2.2.10 and let me know what happens.
