### ISSUE TITLE
MySQL/Aurora/MariaDB Support

### ISSUE THREAD

**Issue by gregmac** [jonwagner/Insight.Database.Schema#55]
I don't see anything specific about this being for MS SQL Server, but nothing says it works with anything else, either. 

Any interest in making this compatible with other DBMSs? My immediate case is for AWS Aurora but that would include MySQL and MariaDB. 

I've only been playing with this a little bit but so far I've run into:
- Doesn't understand backticks (used for quoting literal object names)
- Runs incompatible SQL to check for Aurora (`SELECT CONVERT(bit, CASE WHEN SERVERPROPERTY('edition') = 'SQL Azure' THEN 1 ELSE 0 END)`)

Just want to ask before I fork and put some effort into this.

**Comment by jonwagner** [comment]
I think you could adapt the structure of the code to work on other platforms, but the project itself isn't designed to be cross-database at this time.
