### ISSUE TITLE
Insight.Database.Scheme.Tests.dll.config missing

### ISSUE THREAD

**Issue by steveadoo32** [jonwagner/Insight.Database.Schema#59]
The [tests project references 'Insight.Database.Schema.Tests.dll.config'](https://github.com/jonwagner/Insight.Database.Schema/blob/master/Insight.Database.Schema.Tests/Insight.Database.Schema.Tests.csproj#L62) but it doesn't look like it's checked into git.

It's set to Copy to Output Directory so I think this is probably needed?

**Comment by jonwagner** [comment]
Added the config file
